[tools]
"github:tj/node-prune" = "latest"
hk = { version = "latest", postinstall = "hk install --mise" }
node = { version = "latest" }
"npm:corepack" = { version = "latest", postinstall = "corepack enable" }
opencode = "latest"

[env]
MSSQL_DB = "northwind"
MSSQL_USER = "instnwnd"
MSSQL_PASSWORD = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYmFiSWZNV0hOT3BBM3QrY052VmtIOFFoTnBORkhVeEl4cnZZL3RoWm4wClNJUTgxelFMaXIzVmNWWWxSSE9RUVNIcno4WThQRXZyenMwL1NuNjZKYWMKLT4gWDI1NTE5IElwcmVrWUN1bUozUU1BbmFPK25CL1RMVzFOYWVZbVA0dkgwSHBCckFXV0EKNXNvRFdlek55MWdKQ0tSQzcwLzkrZ0tJZ09KQVNTOHNmb3VacDFWK294SQotPiBzc2gtZWQyNTUxOSBWQi93QXcgUFdwY1B4WXlGalpyM2RYK3RJNWU0eDM1YkU3MytyRExMa04xRUxEREJRZwovdkxnZ2hDdlNGQXVmZWxodXo5VDBLa3c2TEprQ05ZQWFqV0JJZnVhVWFzCi0+ID06am0tZ3JlYXNlIFA/SjkgJjxfOXN7SkwKV1p2Ynl6c25zaVNRRmovVUFVQkRXMTJzN25HZEQxa2V6Zk5BQjlHdVJMNzVDMHJxajUzT3VhQ1lsY2RtTHVqNApGdwotLS0gdVM0NHBmRURhVHE5dzVTUlEwT3cwS2lxRE1nbVZjTUZ4ZGwxb3NMRTRWcwq0kzVDS1/CqvSYcgtDGnW5NzvGIJ3lDlSlGcznONY7jnIua89WDtOch1oKmTQQo11SBv1oOdpt" }
MSSQL_SA_PASSWORD = { age = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VlQ0VC9rS3BjL29HWEZwZU5UQWpOTUY1bTZrNHdZbHFVbWV1clZubXdBClBoSDJUNVRXVEhYL3U2a3VITXRGRjRTWm9XcGNoSm5pUUk4cDNSQndFdVkKLT4gWDI1NTE5IEJKbHhJSjRXTHI3NWlNYlRCb2V0cHp6TFNDSllWRGF6cXdsUkR5YmZ6SE0KWTlnYnJzUitBVHV3THduYXN0azR1YnEvZi9JbnNlVCtNc2xodXBpbldhdwotPiBzc2gtZWQyNTUxOSBWQi93QXcgOEVLRDlKQWRBZnREaTB5N1FwUTZPclpwcEZ6eEhaZUcvc09MdWMvaGVrWQpRQWhhVlRTOFEyRXFXRzZvU0lXeVNBdzRHTHd5UWkvVXZ5VGFFejJqczBrCi0+IDB7Oi1ncmVhc2UgZDZyCkNTdWQ5a2Q2dHh0YUJEemREalFBclhnUmdSaTlHWUpYbXRuVnpGbXJDSFNLRWhTR1BBRThMeXkwK29rVW1tVDgKaXRSWnYwL3dOazh0RFJ4L0lFSmMwdWk0ZmU4Ci0tLSAyS1A0MitybG1zejhKTWxXc3BYTkxsSXNWaldYNk9oOWlPSnBtdzU4bktBCuzs5JeDVyiPIqmBqj0OztJeYVmXCilN+dy+ePIozFSIXgHhyC6X1QxHQn9xuz9RlUlWL4bFaA" }
_.file = ".env"
_.path = ["{{config_root}}/node_modules/.bin"]
HK_MISE = 1

[settings]
experimental = true
env_shell_expand = true
node.corepack = true

[hooks]
postinstall = { task = "pnpm-install" }

[tasks.pnpm-install]
description = "Installs dependencies with pnpm"
run = "pnpm install"
sources = ["package.json", "pnpm-lock.yaml", "pnpm-workspace.yaml", "mise.toml"]
outputs = ["node_modules/.pnpm/lock.yaml"]

[tasks.build-and-clean]
description = "Build the app and clean node_modules"
run = ["pnpm run build", "pnpm prune --prod", "node-prune"]
env = { NODE_ENV = "production", CI = "1" }
sources = [
  "package.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "tsconfig.json",
  "tsconfig.build.json",
]
outputs = ["dist/tsconfig.build.tsbuildinfo"]
