apiVersion: v1
data:
  data-source.js: |
    import { DataSource } from 'typeorm';
    export default new DataSource({
      type: 'mssql',
      host: 'sql-server',
      port: 1433,
      username: process.env.MSSQL_USER ?? 'instnwnd',
      password: process.env.MSSQL_PASSWORD,
      database: process.env.MSSQL_DB ?? 'northwind',
      synchronize: false,
      migrations: ['database/migrations/*.js'],
      seeds: ['database/seeds/*.seeder.js'],
      options: {
        encrypt: false,
        trustServerCertificate: true,
        appName: 'TypeORM',
      },
    });
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: migrations
  name: data-source
