services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:5-24-trixie@sha256:4c09888a2acdaf619daa79d2e811329536450a1045be9243fe03d4b02c81e91e
    command: sleep infinity
    user: node
    volumes:
      - ..:/workspaces/nest-northwind-api:cached
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:4bab24f36c1ecd48e85f7d37df26e6bf301641d84c3fe652f9a0dcc947d512e1
    user: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: ${MSSQL_PID:-Developer}
      MSSQL_LCID: 3082
      MSSQL_ENABLE_HADR: '1'
      MSSQL_AGENT_ENABLED: 'true'
      MSSQL_DB: ${MSSQL_DB:-northwind}
      MSSQL_USER: ${MSSQL_USER:-instnwnd}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    network_mode: service:workspace
    volumes:
      - sql-server-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -h -1 -t 1 -C -b -U $${MSSQL_USER:-sa} -P $${MSSQL_PASSWORD:-MSSQL_SA_PASSWORD} -Q "SELECT name FROM sys.databases WHERE name = N'$${MSSQL_DB:-master}'"
      interval: 10s
      timeout: 5s
      retries: 5
  oauth:
    image: pocketid/pocket-id:v2
    environment:
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-}
      APP_URL: ${APP_URL:-http://localhost:1411}
      VERSION_CHECK_DISABLED: 'true'
      ANALYTICS_DISABLED: 'true'
    network_mode: service:workspace
    volumes:
      - pocket-id-data:/app/data

volumes:
  sql-server-data:
  pocket-id-data:
