services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:5-24-trixie@sha256:627da5f4ab0dfa32c23cd93a10925c20bf92e5f2814cec74cde8520fb33e3ec4
    command: sleep infinity
    user: node
    volumes:
      - ..:/workspaces/nest-northwind-api:cached
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:86cc6144ef39bb0fbed2329e1ad79b13ee82e7b2e4739213a0db0800e668a74a
    user: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: ${MSSQL_PID:-Developer}
      MSSQL_LCID: 3082
      MSSQL_ENABLE_HADR: '1'
      MSSQL_AGENT_ENABLED: 'true'
      MSSQL_DB: ${MSSQL_DB:-northwind}
      MSSQL_USER: ${MSSQL_USER:-instnwnd}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    network_mode: service:workspace
    volumes:
      - sql-server-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -h -1 -t 1 -C -b -U $${MSSQL_USER:-sa} -P $${MSSQL_PASSWORD:-MSSQL_SA_PASSWORD} -Q "SELECT name FROM sys.databases WHERE name = N'$${MSSQL_DB:-master}'"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql-server-data:
