services:
  workspace:
    image: ghcr.io/bare-devcontainer/mise:trixie@sha256:96b949b54794a0a1e1f9a337901239e31c8c918c8c2b99ebc1557225f73e8892
    command: sleep infinity
    init: true
    volumes:
      - ..:/workspaces/nest-northwind-api:cached
  sql-server:
    image: mcr.microsoft.com/mssql/server:2025-latest@sha256:2b5b581621126574f3d1f75e78d3eebe8d05aedb59ad0cfdf9aa42cb0634d726
    user: mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: ${MSSQL_PID:-Developer}
      MSSQL_LCID: 3082
      MSSQL_ENABLE_HADR: '1'
      MSSQL_AGENT_ENABLED: 'true'
      MSSQL_DB: ${MSSQL_DB:-northwind}
      MSSQL_USER: ${MSSQL_USER:-instnwnd}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    network_mode: service:workspace
    volumes:
      - sql-server-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -h -1 -t 1 -C -b -U $${MSSQL_USER:-sa} -P $${MSSQL_PASSWORD:-MSSQL_SA_PASSWORD} -Q "SELECT name FROM sys.databases WHERE name = N'$${MSSQL_DB:-master}'"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql-server-data:
