import type { DataSource, Repository } from 'typeorm';
import { Seeder } from 'typeorm-extension';

import { Order } from '../../order/entities/order.entity';
import { OrderDetail } from '../../order/entities/order-detail.entity';
import { Customer } from '../../customer/entities/customer.entity';
import { Employee } from '../../employee/entities/employee.entity';
import { Shipper } from '../../shipper/entities/shipper.entity';
import { Product } from '../../product/entities/product.entity';

const orderFixtures = [
  {
    id: 10248,
    customerCode: 'VINET',
    employeeId: 5,
    orderDate: '7/4/1996',
    requiredDate: '8/1/1996',
    shippedDate: '7/16/1996',
    shipVia: 3,
    freight: 32.38,
    shipName: 'Vins et alcools Chevalier',
    shipAddress: "59 rue de l'Abbaye",
    shipCity: 'Reims',
    shipRegion: null,
    shipPostalCode: '51100',
    shipCountry: 'France',
  },
  {
    id: 10249,
    customerCode: 'TOMSP',
    employeeId: 6,
    orderDate: '7/5/1996',
    requiredDate: '8/16/1996',
    shippedDate: '7/10/1996',
    shipVia: 1,
    freight: 11.61,
    shipName: 'Toms Spezialitäten',
    shipAddress: 'Luisenstr. 48',
    shipCity: 'Münster',
    shipRegion: null,
    shipPostalCode: '44087',
    shipCountry: 'Germany',
  },
  {
    id: 10250,
    customerCode: 'HANAR',
    employeeId: 4,
    orderDate: '7/8/1996',
    requiredDate: '8/5/1996',
    shippedDate: '7/12/1996',
    shipVia: 2,
    freight: 65.83,
    shipName: 'Hanari Carnes',
    shipAddress: 'Rua do Paço, 67',
    shipCity: 'Rio de Janeiro',
    shipRegion: 'RJ',
    shipPostalCode: '05454-876',
    shipCountry: 'Brazil',
  },
  {
    id: 10251,
    customerCode: 'VICTE',
    employeeId: 3,
    orderDate: '7/8/1996',
    requiredDate: '8/5/1996',
    shippedDate: '7/15/1996',
    shipVia: 1,
    freight: 41.34,
    shipName: 'Victuailles en stock',
    shipAddress: '2, rue du Commerce',
    shipCity: 'Lyon',
    shipRegion: null,
    shipPostalCode: '69004',
    shipCountry: 'France',
  },
  {
    id: 10252,
    customerCode: 'SUPRD',
    employeeId: 4,
    orderDate: '7/9/1996',
    requiredDate: '8/6/1996',
    shippedDate: '7/11/1996',
    shipVia: 2,
    freight: 51.3,
    shipName: 'Suprêmes délices',
    shipAddress: 'Boulevard Tirou, 255',
    shipCity: 'Charleroi',
    shipRegion: null,
    shipPostalCode: 'B-6000',
    shipCountry: 'Belgium',
  },
  {
    id: 10253,
    customerCode: 'HANAR',
    employeeId: 3,
    orderDate: '7/10/1996',
    requiredDate: '7/24/1996',
    shippedDate: '7/16/1996',
    shipVia: 2,
    freight: 58.17,
    shipName: 'Hanari Carnes',
    shipAddress: 'Rua do Paço, 67',
    shipCity: 'Rio de Janeiro',
    shipRegion: 'RJ',
    shipPostalCode: '05454-876',
    shipCountry: 'Brazil',
  },
  {
    id: 10254,
    customerCode: 'CHOPS',
    employeeId: 5,
    orderDate: '7/11/1996',
    requiredDate: '8/8/1996',
    shippedDate: '7/23/1996',
    shipVia: 2,
    freight: 22.98,
    shipName: 'Chop-suey Chinese',
    shipAddress: 'Hauptstr. 31',
    shipCity: 'Bern',
    shipRegion: null,
    shipPostalCode: '3012',
    shipCountry: 'Switzerland',
  },
  {
    id: 10255,
    customerCode: 'RICSU',
    employeeId: 9,
    orderDate: '7/12/1996',
    requiredDate: '8/9/1996',
    shippedDate: '7/15/1996',
    shipVia: 3,
    freight: 148.33,
    shipName: 'Richter Supermarkt',
    shipAddress: 'Starenweg 5',
    shipCity: 'Genève',
    shipRegion: null,
    shipPostalCode: '1204',
    shipCountry: 'Switzerland',
  },
  {
    id: 10256,
    customerCode: 'WELLI',
    employeeId: 3,
    orderDate: '7/15/1996',
    requiredDate: '8/12/1996',
    shippedDate: '7/17/1996',
    shipVia: 2,
    freight: 13.97,
    shipName: 'Wellington Importadora',
    shipAddress: 'Rua do Mercado, 12',
    shipCity: 'Resende',
    shipRegion: 'SP',
    shipPostalCode: '08737-363',
    shipCountry: 'Brazil',
  },
  {
    id: 10257,
    customerCode: 'HILAA',
    employeeId: 4,
    orderDate: '7/16/1996',
    requiredDate: '8/13/1996',
    shippedDate: '7/22/1996',
    shipVia: 3,
    freight: 81.91,
    shipName: 'HILARION-Abastos',
    shipAddress: 'Carrera 22 con Ave. Carlos Soublette #8-35',
    shipCity: 'San Cristóbal',
    shipRegion: 'Táchira',
    shipPostalCode: '5022',
    shipCountry: 'Venezuela',
  },
  {
    id: 10258,
    customerCode: 'ERNSH',
    employeeId: 1,
    orderDate: '7/17/1996',
    requiredDate: '8/14/1996',
    shippedDate: '7/23/1996',
    shipVia: 1,
    freight: 140.51,
    shipName: 'Ernst Handel',
    shipAddress: 'Kirchgasse 6',
    shipCity: 'Graz',
    shipRegion: null,
    shipPostalCode: '8010',
    shipCountry: 'Austria',
  },
  {
    id: 10259,
    customerCode: 'CENTC',
    employeeId: 4,
    orderDate: '7/18/1996',
    requiredDate: '8/15/1996',
    shippedDate: '7/25/1996',
    shipVia: 3,
    freight: 3.25,
    shipName: 'Centro comercial Moctezuma',
    shipAddress: 'Sierras de Granada 9993',
    shipCity: 'México D.F.',
    shipRegion: null,
    shipPostalCode: '05022',
    shipCountry: 'Mexico',
  },
  {
    id: 10260,
    customerCode: 'OTTIK',
    employeeId: 4,
    orderDate: '7/19/1996',
    requiredDate: '8/16/1996',
    shippedDate: '7/29/1996',
    shipVia: 1,
    freight: 55.09,
    shipName: 'Ottilies Käseladen',
    shipAddress: 'Mehrheimerstr. 369',
    shipCity: 'Köln',
    shipRegion: null,
    shipPostalCode: '50739',
    shipCountry: 'Germany',
  },
  {
    id: 10261,
    customerCode: 'QUEDE',
    employeeId: 4,
    orderDate: '7/19/1996',
    requiredDate: '8/16/1996',
    shippedDate: '7/30/1996',
    shipVia: 2,
    freight: 3.05,
    shipName: 'Que Delícia',
    shipAddress: 'Rua da Panificadora, 12',
    shipCity: 'Rio de Janeiro',
    shipRegion: 'RJ',
    shipPostalCode: '02389-673',
    shipCountry: 'Brazil',
  },
  {
    id: 10262,
    customerCode: 'RATTC',
    employeeId: 8,
    orderDate: '7/22/1996',
    requiredDate: '8/19/1996',
    shippedDate: '7/25/1996',
    shipVia: 3,
    freight: 48.29,
    shipName: 'Rattlesnake Canyon Grocery',
    shipAddress: '2817 Milton Dr.',
    shipCity: 'Albuquerque',
    shipRegion: 'NM',
    shipPostalCode: '87110',
    shipCountry: 'USA',
  },
  {
    id: 10263,
    customerCode: 'ERNSH',
    employeeId: 9,
    orderDate: '7/23/1996',
    requiredDate: '8/20/1996',
    shippedDate: '7/31/1996',
    shipVia: 3,
    freight: 146.06,
    shipName: 'Ernst Handel',
    shipAddress: 'Kirchgasse 6',
    shipCity: 'Graz',
    shipRegion: null,
    shipPostalCode: '8010',
    shipCountry: 'Austria',
  },
  {
    id: 10264,
    customerCode: 'FOLKO',
    employeeId: 6,
    orderDate: '7/24/1996',
    requiredDate: '8/21/1996',
    shippedDate: '8/23/1996',
    shipVia: 3,
    freight: 3.67,
    shipName: 'Folk och fä HB',
    shipAddress: 'Åkergatan 24',
    shipCity: 'Bräcke',
    shipRegion: null,
    shipPostalCode: 'S-844 67',
    shipCountry: 'Sweden',
  },
  {
    id: 10265,
    customerCode: 'BLONP',
    employeeId: 2,
    orderDate: '7/25/1996',
    requiredDate: '8/22/1996',
    shippedDate: '8/12/1996',
    shipVia: 1,
    freight: 55.28,
    shipName: 'Blondel père et fils',
    shipAddress: '24, place Kléber',
    shipCity: 'Strasbourg',
    shipRegion: null,
    shipPostalCode: '67000',
    shipCountry: 'France',
  },
  {
    id: 10266,
    customerCode: 'WARTH',
    employeeId: 3,
    orderDate: '7/26/1996',
    requiredDate: '9/6/1996',
    shippedDate: '7/31/1996',
    shipVia: 3,
    freight: 25.73,
    shipName: 'Wartian Herkku',
    shipAddress: 'Torikatu 38',
    shipCity: 'Oulu',
    shipRegion: null,
    shipPostalCode: '90110',
    shipCountry: 'Finland',
  },
  {
    id: 10267,
    customerCode: 'FRANK',
    employeeId: 4,
    orderDate: '7/29/1996',
    requiredDate: '8/26/1996',
    shippedDate: '8/6/1996',
    shipVia: 1,
    freight: 208.58,
    shipName: 'Frankenversand',
    shipAddress: 'Berliner Platz 43',
    shipCity: 'München',
    shipRegion: null,
    shipPostalCode: '80805',
    shipCountry: 'Germany',
  },
  {
    id: 10268,
    customerCode: 'GROSR',
    employeeId: 8,
    orderDate: '7/30/1996',
    requiredDate: '8/27/1996',
    shippedDate: '8/2/1996',
    shipVia: 3,
    freight: 66.29,
    shipName: 'GROSELLA-Restaurante',
    shipAddress: '5ª Ave. Los Palos Grandes',
    shipCity: 'Caracas',
    shipRegion: 'DF',
    shipPostalCode: '1081',
    shipCountry: 'Venezuela',
  },
  {
    id: 10269,
    customerCode: 'WHITC',
    employeeId: 5,
    orderDate: '7/31/1996',
    requiredDate: '8/14/1996',
    shippedDate: '8/9/1996',
    shipVia: 1,
    freight: 4.56,
    shipName: 'White Clover Markets',
    shipAddress: '1029 - 12th Ave. S.',
    shipCity: 'Seattle',
    shipRegion: 'WA',
    shipPostalCode: '98124',
    shipCountry: 'USA',
  },
  {
    id: 10270,
    customerCode: 'WARTH',
    employeeId: 1,
    orderDate: '8/1/1996',
    requiredDate: '8/29/1996',
    shippedDate: '8/2/1996',
    shipVia: 1,
    freight: 136.54,
    shipName: 'Wartian Herkku',
    shipAddress: 'Torikatu 38',
    shipCity: 'Oulu',
    shipRegion: null,
    shipPostalCode: '90110',
    shipCountry: 'Finland',
  },
  {
    id: 10271,
    customerCode: 'SPLIR',
    employeeId: 6,
    orderDate: '8/1/1996',
    requiredDate: '8/29/1996',
    shippedDate: '8/30/1996',
    shipVia: 2,
    freight: 4.54,
    shipName: 'Split Rail Beer & Ale',
    shipAddress: 'P.O. Box 555',
    shipCity: 'Lander',
    shipRegion: 'WY',
    shipPostalCode: '82520',
    shipCountry: 'USA',
  },
  {
    id: 10272,
    customerCode: 'RATTC',
    employeeId: 6,
    orderDate: '8/2/1996',
    requiredDate: '8/30/1996',
    shippedDate: '8/6/1996',
    shipVia: 2,
    freight: 98.03,
    shipName: 'Rattlesnake Canyon Grocery',
    shipAddress: '2817 Milton Dr.',
    shipCity: 'Albuquerque',
    shipRegion: 'NM',
    shipPostalCode: '87110',
    shipCountry: 'USA',
  },
  {
    id: 10273,
    customerCode: 'QUICK',
    employeeId: 3,
    orderDate: '8/5/1996',
    requiredDate: '9/2/1996',
    shippedDate: '8/12/1996',
    shipVia: 3,
    freight: 76.07,
    shipName: 'QUICK-Stop',
    shipAddress: 'Taucherstraße 10',
    shipCity: 'Cunewalde',
    shipRegion: null,
    shipPostalCode: '01307',
    shipCountry: 'Germany',
  },
  {
    id: 10274,
    customerCode: 'VINET',
    employeeId: 6,
    orderDate: '8/6/1996',
    requiredDate: '9/3/1996',
    shippedDate: '8/16/1996',
    shipVia: 1,
    freight: 6.01,
    shipName: 'Vins et alcools Chevalier',
    shipAddress: "59 rue de l'Abbaye",
    shipCity: 'Reims',
    shipRegion: null,
    shipPostalCode: '51100',
    shipCountry: 'France',
  },
  {
    id: 10275,
    customerCode: 'MAGAA',
    employeeId: 1,
    orderDate: '8/7/1996',
    requiredDate: '9/4/1996',
    shippedDate: '8/9/1996',
    shipVia: 1,
    freight: 26.93,
    shipName: 'Magazzini Alimentari Riuniti',
    shipAddress: 'Via Ludovico il Moro 22',
    shipCity: 'Bergamo',
    shipRegion: null,
    shipPostalCode: '24100',
    shipCountry: 'Italy',
  },
  {
    id: 10276,
    customerCode: 'TORTU',
    employeeId: 8,
    orderDate: '8/8/1996',
    requiredDate: '8/22/1996',
    shippedDate: '8/14/1996',
    shipVia: 3,
    freight: 13.84,
    shipName: 'Tortuga Restaurante',
    shipAddress: 'Avda. Azteca 123',
    shipCity: 'México D.F.',
    shipRegion: null,
    shipPostalCode: '05033',
    shipCountry: 'Mexico',
  },
  {
    id: 10277,
    customerCode: 'MORGK',
    employeeId: 2,
    orderDate: '8/9/1996',
    requiredDate: '9/6/1996',
    shippedDate: '8/13/1996',
    shipVia: 3,
    freight: 125.77,
    shipName: 'Morgenstern Gesundkost',
    shipAddress: 'Heerstr. 22',
    shipCity: 'Leipzig',
    shipRegion: null,
    shipPostalCode: '04179',
    shipCountry: 'Germany',
  },
  {
    id: 10278,
    customerCode: 'BERGS',
    employeeId: 8,
    orderDate: '8/12/1996',
    requiredDate: '9/9/1996',
    shippedDate: '8/16/1996',
    shipVia: 2,
    freight: 92.69,
    shipName: 'Berglunds snabbköp',
    shipAddress: 'Berguvsvägen  8',
    shipCity: 'Luleå',
    shipRegion: null,
    shipPostalCode: 'S-958 22',
    shipCountry: 'Sweden',
  },
  {
    id: 10279,
    customerCode: 'LEHMS',
    employeeId: 8,
    orderDate: '8/13/1996',
    requiredDate: '9/10/1996',
    shippedDate: '8/16/1996',
    shipVia: 2,
    freight: 25.83,
    shipName: 'Lehmanns Marktstand',
    shipAddress: 'Magazinweg 7',
    shipCity: 'Frankfurt a.M.',
    shipRegion: null,
    shipPostalCode: '60528',
    shipCountry: 'Germany',
  },
  {
    id: 10280,
    customerCode: 'BERGS',
    employeeId: 2,
    orderDate: '8/14/1996',
    requiredDate: '9/11/1996',
    shippedDate: '9/12/1996',
    shipVia: 1,
    freight: 8.98,
    shipName: 'Berglunds snabbköp',
    shipAddress: 'Berguvsvägen  8',
    shipCity: 'Luleå',
    shipRegion: null,
    shipPostalCode: 'S-958 22',
    shipCountry: 'Sweden',
  },
  {
    id: 10281,
    customerCode: 'ROMEY',
    employeeId: 4,
    orderDate: '8/14/1996',
    requiredDate: '8/28/1996',
    shippedDate: '8/21/1996',
    shipVia: 1,
    freight: 2.94,
    shipName: 'Romero y tomillo',
    shipAddress: 'Gran Vía, 1',
    shipCity: 'Madrid',
    shipRegion: null,
    shipPostalCode: '28001',
    shipCountry: 'Spain',
  },
  {
    id: 10282,
    customerCode: 'ROMEY',
    employeeId: 4,
    orderDate: '8/15/1996',
    requiredDate: '9/12/1996',
    shippedDate: '8/21/1996',
    shipVia: 1,
    freight: 12.69,
    shipName: 'Romero y tomillo',
    shipAddress: 'Gran Vía, 1',
    shipCity: 'Madrid',
    shipRegion: null,
    shipPostalCode: '28001',
    shipCountry: 'Spain',
  },
];

const orderDetailFixtures = [
  { orderId: 10248, productId: 11, unitPrice: 14, quantity: 12, discount: 0 },
  { orderId: 10248, productId: 42, unitPrice: 9.8, quantity: 10, discount: 0 },
  { orderId: 10248, productId: 72, unitPrice: 34.8, quantity: 5, discount: 0 },
  { orderId: 10249, productId: 14, unitPrice: 18.6, quantity: 9, discount: 0 },
  { orderId: 10249, productId: 51, unitPrice: 42.4, quantity: 40, discount: 0 },
  { orderId: 10250, productId: 41, unitPrice: 7.7, quantity: 10, discount: 0 },
  {
    orderId: 10250,
    productId: 51,
    unitPrice: 42.4,
    quantity: 35,
    discount: 0.15,
  },
  {
    orderId: 10250,
    productId: 65,
    unitPrice: 16.8,
    quantity: 15,
    discount: 0.15,
  },
  {
    orderId: 10251,
    productId: 22,
    unitPrice: 16.8,
    quantity: 6,
    discount: 0.05,
  },
  {
    orderId: 10251,
    productId: 57,
    unitPrice: 15.6,
    quantity: 15,
    discount: 0.05,
  },
  { orderId: 10251, productId: 65, unitPrice: 16.8, quantity: 20, discount: 0 },
  {
    orderId: 10252,
    productId: 20,
    unitPrice: 64.8,
    quantity: 40,
    discount: 0.05,
  },
  { orderId: 10252, productId: 33, unitPrice: 2, quantity: 25, discount: 0.05 },
  { orderId: 10252, productId: 60, unitPrice: 27.2, quantity: 40, discount: 0 },
];

function parseDate(dateStr: string): Date {
  const parts = dateStr.split('/');

  return new Date(
    Number.parseInt(parts[2], 10),
    Number.parseInt(parts[0], 10) - 1,
    Number.parseInt(parts[1], 10),
  );
}

export default class OrderSeeder implements Seeder {
  async run(dataSource: DataSource) {
    const customerRepo: Repository<Customer> =
      dataSource.getRepository(Customer);
    const employeeRepo: Repository<Employee> =
      dataSource.getRepository(Employee);
    const shipperRepo: Repository<Shipper> = dataSource.getRepository(Shipper);
    const productRepo: Repository<Product> = dataSource.getRepository(Product);

    const customers = await customerRepo.find();
    const employees = await employeeRepo.find();
    const shippers = await shipperRepo.find();
    const products = await productRepo.find();

    const customerMap = new Map<string, Customer>(
      customers.map((c) => [c.code, c]),
    );
    const employeeMap = new Map<number, Employee>(
      employees.map((e) => [e.id, e]),
    );
    const shipperMap = new Map<number, Shipper>(shippers.map((s) => [s.id, s]));
    const productMap = new Map<number, Product>(products.map((p) => [p.id, p]));

    await dataSource.transaction(async (manager) => {
      const orderRepository = manager.getRepository(Order);
      const detailRepository = manager.getRepository(OrderDetail);

      for (const f of orderFixtures) {
        const customer = customerMap.get(f.customerCode);
        const employee = employeeMap.get(f.employeeId);
        const shipVia = shipperMap.get(f.shipVia);

        if (!customer || !employee || !shipVia) {
          continue;
        }

        const order = Object.assign(new Order(), {
          id: f.id,
          customer,
          employee,
          orderDate: parseDate(f.orderDate),
          requiredDate: parseDate(f.requiredDate),
          shippedDate: parseDate(f.shippedDate),
          shipVia,
          freight: f.freight,
          shipName: f.shipName,
          shipAddress: f.shipAddress,
          shipCity: f.shipCity,
          shipRegion: f.shipRegion,
          shipPostalCode: f.shipPostalCode,
          shipCountry: f.shipCountry,
        });

        const existing = await orderRepository.findOne({
          where: { id: f.id },
          select: { id: true },
        });

        if (existing) {
          const { id, ...partialEntity } = order;
          await orderRepository.update({ id }, partialEntity);
        } else {
          await orderRepository.save(order);
        }
      }

      for (const f of orderDetailFixtures) {
        const product = productMap.get(f.productId);

        if (!product) {
          continue;
        }

        const detail = Object.assign(new OrderDetail(), {
          orderId: f.orderId,
          productId: f.productId,
          unitPrice: f.unitPrice,
          quantity: f.quantity,
          discount: f.discount,
          product,
        });

        const existing = await detailRepository.findOne({
          where: { orderId: f.orderId, productId: f.productId },
          select: { orderId: true, productId: true },
        });

        if (!existing) {
          await detailRepository.save(detail);
        }
      }
    });
  }
}
