name: Publish the Docker images 🐋

on:
  push:

jobs:
  docker-bake:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Set up Docker Buildx 🐳
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e

      - name: Build 🏗️
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b
        with:
          push: true
          set: |
            api.tags=ttl.sh/api-${{ github.sha }}:1h
            migrations.tags=ttl.sh/migrations-${{ github.sha }}:1h
            *.cache-to=type=registry,ref=ttl.sh/${{ github.sha }}:1h,mode=max

  test-k8s:
    runs-on: ubuntu-latest
    needs:
      - docker-bake
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Create a ephemeral Kubernetes cluster with Kind ⚓
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc

      - name: Verify Cluster Connection
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Replace values
        run: |
          yq -i '.spec.template.spec.containers.[0].image = ttl.sh/api-${{ github.sha }}:1h' k8s/server-deployment.yaml
          yq -i '.spec.template.spec.containers.[0].image = ttl.sh/migrations-${{ github.sha }}:1h' k8s/migrations-job.yaml
          yq '.stringData.MSSQL_PASSWORD = "${{ github.sha }}" | .stringData.MSSQL_SA_PASSWORD = "${{ github.sha }}"' k8s/database-secret.example.yaml | yq -Poy k8s/database-secret.yaml

      - name: Deploy SQL Server
        run: |
          kubectl apply -f k8s/database-secret.yaml
          kubectl apply -f k8s/sql-server-data-persistentvolumeclaim.yaml
          kubectl apply -f k8s/sql-server-deployment.yaml
          kubectl apply -f k8s/sql-server-service.yaml
          kubectl rollout status sql-server --timeout=90s

      - name: Run migrations job
        run: |
          kubectl apply -f k8s/data-source-configmap.yaml
          kubectl apply -f k8s/migrations-job.yaml

      - name: Deploy the API server
        run: |
          kubectl apply -f k8s/server-deployment.yaml
          kubectl apply -f k8s/server-service.yaml
          kubectl rollout status server --timeout=30s

      - name: Forward the port
        background: true
        run: kubectl port-forward server 3000:3000

      - name: Wait for the server
        uses: harryvasanth/wait-for-http-endpoint@e56e03998cd4799fa97f17ce54a3d0ed62f8e02c
        with:
          url: http://localhost:3000

      - name: Run bruno tests
        uses: usebruno/bruno-cli-action@104e180c2e7219a915dc48b6979ddbafe0940fcd
        with:
          working-directory: test/e2e
          command: run --env development

      - name: Print cluster status on failure
        if: failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl get events --sort-by='.metadata.creationTimestamp'
