name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release the new version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1
        id: app-token
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup PNPM
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2
        with:
          cache: true

      - name: Semantic release
        run: >-
          pnx --package=@semantic-release/changelog
          --package=@semantic-release/git
          --package=semantic-release
          semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
